# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class SkidfuscatorJavaObfuscator < Formula
  desc "Public proof-of-concept obfuscator using the mapleir framework designed by cts &amp;"
  homepage "https://github.com/skidfuscatordev/skidfuscator-java-obfuscator"
  url "https://github.com/skidfuscatordev/skidfuscator-java-obfuscator/archive/refs/tags/2.0.11.tar.gz"
  sha256 "52579b2b699b701395892f665677a3295bf35b3d51ebb8c7986cedb214ab76c6"
  license "MIT"

  def install
    libexec.install Dir["*.jar"]
jar_name = Dir["#{libexec}/*.jar"].first
(bin/"skidfuscator").write <<~EOS
  #!/usr/bin/env bash
  exec java -jar "#{jar_name}" "$@"
EOS
(bin/"skidfuscator").chmod 0755
  end

  test do
    assert_match("Usage", shell_output("#{bin}/skidfuscator --help", 0))
  end
end
